# Based on https://github.com/ajour/ajour/blob/6dbe8f18fcdd6ef8e894a473931c1a84ef5f94b9/.github/workflows/release_to_draft.yml
# TODO: run on tag push?

on:
  push:
    branches:
      - main
      - build
    paths:
      - '**.rs'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'resources'
      - '.github/workflows'
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'resources'
      - '.github/workflows'

name: "Build binaries"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        target:
          - target: windows
            os: windows-latest
            make: make binary
            binary_path: target/release/ajour.exe

          - target: linux
            os: ubuntu-latest
            make: make appimage
            binary_path: ajour.AppImage

          - target: macos
            os: macos-latest
            make: make dmg MACOS=1
            binary_path: target/release/osx/ajour.dmg
          - target: macos-tar
            os: macos-latest
            make: make tar MACOS=1
            binary_path: target/release/ajour.tar.gz

    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        if: ${{ matrix.target.os == 'ubuntu-latest' }}
        run: sudo apt update && sudo apt install libxkbcommon-dev libgtk-3-dev

      - name: Do we need linuxdeploy?
        if: ${{ matrix.target.os == 'ubuntu-latest' }}
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

      - name: Do we need GNU tar? # Fix for macos caching, https://github.com/actions/cache/issues/403
        if: ${{ matrix.target.os == 'macos-latest' }}
        run: |
          brew install gnu-tar
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH

      - name: Build
        run: ${{ matrix.target.make }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.target }}
          path: ${{ matrix.target.binary_path }}
